/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudioProductIdRouteImport } from './routes/studio.$productId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as AdsAdIdRouteImport } from './routes/ads.$adId'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminPromptsRouteImport } from './routes/admin.prompts'
import { Route as AdminPlaygroundRouteImport } from './routes/admin.playground'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AccountBrandRouteImport } from './routes/account.brand'
import { Route as AccountBillingRouteImport } from './routes/account.billing'
import { Route as StudioProductIdStrategyRouteImport } from './routes/studio.$productId.strategy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudioProductIdRoute = StudioProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => StudioRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsAdIdRoute = AdsAdIdRouteImport.update({
  id: '/ads/$adId',
  path: '/ads/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AccountBrandRoute = AccountBrandRouteImport.update({
  id: '/account/brand',
  path: '/account/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProductIdStrategyRoute = StudioProductIdStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => StudioProductIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/playground'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/boards/$boardId'
    | '/studio/$productId'
    | '/admin/'
    | '/studio/'
    | '/studio/$productId/strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/playground'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/boards/$boardId'
    | '/studio/$productId'
    | '/admin'
    | '/studio'
    | '/studio/$productId/strategy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/playground'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/boards/$boardId'
    | '/studio/$productId'
    | '/admin/'
    | '/studio/'
    | '/studio/$productId/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  StudioRoute: typeof StudioRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountBrandRoute: typeof AccountBrandRoute
  AdsAdIdRoute: typeof AdsAdIdRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/studio/$productId': {
      id: '/studio/$productId'
      path: '/$productId'
      fullPath: '/studio/$productId'
      preLoaderRoute: typeof StudioProductIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$adId': {
      id: '/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/ads/$adId'
      preLoaderRoute: typeof AdsAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/brand': {
      id: '/account/brand'
      path: '/account/brand'
      fullPath: '/account/brand'
      preLoaderRoute: typeof AccountBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$productId/strategy': {
      id: '/studio/$productId/strategy'
      path: '/strategy'
      fullPath: '/studio/$productId/strategy'
      preLoaderRoute: typeof StudioProductIdStrategyRouteImport
      parentRoute: typeof StudioProductIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudioProductIdRouteChildren {
  StudioProductIdStrategyRoute: typeof StudioProductIdStrategyRoute
}

const StudioProductIdRouteChildren: StudioProductIdRouteChildren = {
  StudioProductIdStrategyRoute: StudioProductIdStrategyRoute,
}

const StudioProductIdRouteWithChildren = StudioProductIdRoute._addFileChildren(
  StudioProductIdRouteChildren,
)

interface StudioRouteChildren {
  StudioProductIdRoute: typeof StudioProductIdRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProductIdRoute: StudioProductIdRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  StudioRoute: StudioRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountBrandRoute: AccountBrandRoute,
  AdsAdIdRoute: AdsAdIdRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
