/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdTestsRouteImport } from './routes/ad-tests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as StudioProductIdRouteImport } from './routes/studio.$productId'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as AdsAdIdRouteImport } from './routes/ads.$adId'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminPromptsRouteImport } from './routes/admin.prompts'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPlaygroundRouteImport } from './routes/admin.playground'
import { Route as AdminDesignLabRouteImport } from './routes/admin.design-lab'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AccountBrandRouteImport } from './routes/account.brand'
import { Route as AccountBillingRouteImport } from './routes/account.billing'
import { Route as AdminDesignLabIndexRouteImport } from './routes/admin.design-lab.index'
import { Route as StudioProductIdStrategyRouteImport } from './routes/studio.$productId.strategy'
import { Route as AdminDesignLabNewRouteImport } from './routes/admin.design-lab.new'
import { Route as AdminDesignLabLibraryRouteImport } from './routes/admin.design-lab.library'
import { Route as AdminDesignLabGenerateRouteImport } from './routes/admin.design-lab.generate'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdTestsRoute = AdTestsRouteImport.update({
  id: '/ad-tests',
  path: '/ad-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProductIdRoute = StudioProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => StudioRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const AdsAdIdRoute = AdsAdIdRouteImport.update({
  id: '/ads/$adId',
  path: '/ads/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptsRoute = AdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignLabRoute = AdminDesignLabRouteImport.update({
  id: '/design-lab',
  path: '/design-lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AccountBrandRoute = AccountBrandRouteImport.update({
  id: '/account/brand',
  path: '/account/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignLabIndexRoute = AdminDesignLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDesignLabRoute,
} as any)
const StudioProductIdStrategyRoute = StudioProductIdStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => StudioProductIdRoute,
} as any)
const AdminDesignLabNewRoute = AdminDesignLabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminDesignLabRoute,
} as any)
const AdminDesignLabLibraryRoute = AdminDesignLabLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminDesignLabRoute,
} as any)
const AdminDesignLabGenerateRoute = AdminDesignLabGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminDesignLabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-tests': typeof AdTestsRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/design-lab': typeof AdminDesignLabRouteWithChildren
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/products/new': typeof ProductsNewRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/design-lab/generate': typeof AdminDesignLabGenerateRoute
  '/admin/design-lab/library': typeof AdminDesignLabLibraryRoute
  '/admin/design-lab/new': typeof AdminDesignLabNewRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
  '/admin/design-lab/': typeof AdminDesignLabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-tests': typeof AdTestsRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/products/new': typeof ProductsNewRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/admin/design-lab/generate': typeof AdminDesignLabGenerateRoute
  '/admin/design-lab/library': typeof AdminDesignLabLibraryRoute
  '/admin/design-lab/new': typeof AdminDesignLabNewRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
  '/admin/design-lab': typeof AdminDesignLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-tests': typeof AdTestsRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/brand': typeof AccountBrandRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/design-lab': typeof AdminDesignLabRouteWithChildren
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/prompts': typeof AdminPromptsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/ads/$adId': typeof AdsAdIdRoute
  '/products/new': typeof ProductsNewRoute
  '/studio/$productId': typeof StudioProductIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/design-lab/generate': typeof AdminDesignLabGenerateRoute
  '/admin/design-lab/library': typeof AdminDesignLabLibraryRoute
  '/admin/design-lab/new': typeof AdminDesignLabNewRoute
  '/studio/$productId/strategy': typeof StudioProductIdStrategyRoute
  '/admin/design-lab/': typeof AdminDesignLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-tests'
    | '/admin'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/sign-in'
    | '/sign-up'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/design-lab'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/products/new'
    | '/studio/$productId'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/studio/'
    | '/admin/design-lab/generate'
    | '/admin/design-lab/library'
    | '/admin/design-lab/new'
    | '/studio/$productId/strategy'
    | '/admin/design-lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-tests'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/products/new'
    | '/studio/$productId'
    | '/account'
    | '/admin'
    | '/products'
    | '/studio'
    | '/admin/design-lab/generate'
    | '/admin/design-lab/library'
    | '/admin/design-lab/new'
    | '/studio/$productId/strategy'
    | '/admin/design-lab'
  id:
    | '__root__'
    | '/'
    | '/ad-tests'
    | '/admin'
    | '/checkout'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/sign-in'
    | '/sign-up'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/account/billing'
    | '/account/brand'
    | '/admin/audit'
    | '/admin/design-lab'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/prompts'
    | '/admin/templates'
    | '/ads/$adId'
    | '/products/new'
    | '/studio/$productId'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/studio/'
    | '/admin/design-lab/generate'
    | '/admin/design-lab/library'
    | '/admin/design-lab/new'
    | '/studio/$productId/strategy'
    | '/admin/design-lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdTestsRoute: typeof AdTestsRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StudioRoute: typeof StudioRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountBrandRoute: typeof AccountBrandRoute
  AdsAdIdRoute: typeof AdsAdIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-tests': {
      id: '/ad-tests'
      path: '/ad-tests'
      fullPath: '/ad-tests'
      preLoaderRoute: typeof AdTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$productId': {
      id: '/studio/$productId'
      path: '/$productId'
      fullPath: '/studio/$productId'
      preLoaderRoute: typeof StudioProductIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/ads/$adId': {
      id: '/ads/$adId'
      path: '/ads/$adId'
      fullPath: '/ads/$adId'
      preLoaderRoute: typeof AdsAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompts': {
      id: '/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design-lab': {
      id: '/admin/design-lab'
      path: '/design-lab'
      fullPath: '/admin/design-lab'
      preLoaderRoute: typeof AdminDesignLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/brand': {
      id: '/account/brand'
      path: '/account/brand'
      fullPath: '/account/brand'
      preLoaderRoute: typeof AccountBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/design-lab/': {
      id: '/admin/design-lab/'
      path: '/'
      fullPath: '/admin/design-lab/'
      preLoaderRoute: typeof AdminDesignLabIndexRouteImport
      parentRoute: typeof AdminDesignLabRoute
    }
    '/studio/$productId/strategy': {
      id: '/studio/$productId/strategy'
      path: '/strategy'
      fullPath: '/studio/$productId/strategy'
      preLoaderRoute: typeof StudioProductIdStrategyRouteImport
      parentRoute: typeof StudioProductIdRoute
    }
    '/admin/design-lab/new': {
      id: '/admin/design-lab/new'
      path: '/new'
      fullPath: '/admin/design-lab/new'
      preLoaderRoute: typeof AdminDesignLabNewRouteImport
      parentRoute: typeof AdminDesignLabRoute
    }
    '/admin/design-lab/library': {
      id: '/admin/design-lab/library'
      path: '/library'
      fullPath: '/admin/design-lab/library'
      preLoaderRoute: typeof AdminDesignLabLibraryRouteImport
      parentRoute: typeof AdminDesignLabRoute
    }
    '/admin/design-lab/generate': {
      id: '/admin/design-lab/generate'
      path: '/generate'
      fullPath: '/admin/design-lab/generate'
      preLoaderRoute: typeof AdminDesignLabGenerateRouteImport
      parentRoute: typeof AdminDesignLabRoute
    }
  }
}

interface AdminDesignLabRouteChildren {
  AdminDesignLabGenerateRoute: typeof AdminDesignLabGenerateRoute
  AdminDesignLabLibraryRoute: typeof AdminDesignLabLibraryRoute
  AdminDesignLabNewRoute: typeof AdminDesignLabNewRoute
  AdminDesignLabIndexRoute: typeof AdminDesignLabIndexRoute
}

const AdminDesignLabRouteChildren: AdminDesignLabRouteChildren = {
  AdminDesignLabGenerateRoute: AdminDesignLabGenerateRoute,
  AdminDesignLabLibraryRoute: AdminDesignLabLibraryRoute,
  AdminDesignLabNewRoute: AdminDesignLabNewRoute,
  AdminDesignLabIndexRoute: AdminDesignLabIndexRoute,
}

const AdminDesignLabRouteWithChildren = AdminDesignLabRoute._addFileChildren(
  AdminDesignLabRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDesignLabRoute: typeof AdminDesignLabRouteWithChildren
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPromptsRoute: typeof AdminPromptsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDesignLabRoute: AdminDesignLabRouteWithChildren,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPromptsRoute: AdminPromptsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsNewRoute: ProductsNewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface StudioProductIdRouteChildren {
  StudioProductIdStrategyRoute: typeof StudioProductIdStrategyRoute
}

const StudioProductIdRouteChildren: StudioProductIdRouteChildren = {
  StudioProductIdStrategyRoute: StudioProductIdStrategyRoute,
}

const StudioProductIdRouteWithChildren = StudioProductIdRoute._addFileChildren(
  StudioProductIdRouteChildren,
)

interface StudioRouteChildren {
  StudioProductIdRoute: typeof StudioProductIdRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProductIdRoute: StudioProductIdRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdTestsRoute: AdTestsRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StudioRoute: StudioRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountBrandRoute: AccountBrandRoute,
  AdsAdIdRoute: AdsAdIdRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
